### ISSUE TITLE
modulize the data-reduction flow of final_astrometric_reduce.py

### ISSUE THREAD

**Issue by dingswin** [dingswin/psrvlbireduce#7]
In order to make the code more user-friendly and usable for different VLBI observing setups, final_astrometric_reduce.py will be modulized. The preliminary plan is to introduce a 'huge' class called "vlbireduce". The class variable would be those iterating during the run (e.g. runlevel, clversion, snversion, targetcl). Other variables might also join the list of class variable. Those configuration variables (yaml inputs) would stay as external variables. The class methods would be each calibration step. 
To ease diagnosis, the class variables won't be implemented until final stage.

**Comment by dingswin** [comment]
Some class methods need to RETURN some variables that are defined (or modified) as global variables (which will be used again, e.g. leakagedopol from the "run CLCOR to correct EOPs" step). Those variables will be left outside the class. This half enclosed style is easier to begin with.

**Comment by dingswin** [comment]
A part of this modulizing is to unify similar calibration steps. This will improve tidiness while worsen readability (how to keep readability is essential). For example, the 'apply_inbeam_CALIB_solutions' steps for combined/separate IFs might be unified. To serve the unification, 'targetcl' will be deprecated ('clversion' will be copied before calibration on inbeams begin). As such, the form in the two 'apply_inbeam_CALIB_solutions' steps become symmetric. This will be implemented after the first brush of modulizing.

Another thing to look at is the 'calibration and solutions application' pairs. The pairs could be welded together using one function that calls the calibration function and apply its solution. Then the link within the pair becomes obvious. The same should work for the 'variables-preparation and calibration' pairs.

The two sub-issues don't contradict to each other.

**Comment by adamdeller** [comment]
Be careful if joining the derivation and application of calibration solutions into one step, because very often you will want to apply the solutions but not derive them (i.e., you will be using a previously saved set of calibration solutions.  This is for instance always the case if using the "--alwayssave" or "--targetonly" options)

**Comment by adamdeller** [comment]
One other suggestion I had previously made by email, just documenting it here now too: 

you might also want to eventually wrap up every runlevel function in a higher level function that takes care of the printing/logging - this would save a lot of repeated code.  You could have a dictionary containing runlevel, function name, and the amount to increment snversion and clversion by, and the higher level function could 1) do the initial printing, 2) invoke the actual function that does the work for this pipeline step, and then 3) do the incrementing and post-function printing.
